debug:
security:
  user:
    password: password
  sessions: ALWAYS
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**
zuul:
  routes:
    service:
      path: /service/**
      url: http://localhost:9000
    user:
      path: /user/**
      url: http://localhost:8090/ua/user
    oauth:
      path: /auth/**
      url: http://localhost:8090/ua/oauth/
spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html,/**/*.js,/**/*.css
      loginPath: /logins
    client:
      accessTokenUri: http://localhost:8090/ua/oauth/token
      userAuthorizationUri: http://localhost:8090/ua/oauth/authorize
      clientId: sensefy
      clientSecret: sensefysecret
      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://localhost:8090/ua/user
      preferTokenInfo: false
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG