debug:
security:
  user:
    password: password
  sessions: ALWAYS
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**,/fonts/**
zuul:
  routes:
    resource:
      path: /service/api/**
      url: http://localhost:9000
    user:
      path: /user/**
      url: http://localhost:8090/ua/user
    oauth:
      path: /auth/**
      url: http://localhost:8090/ua
    logout:
      path: /logout
      url: http://localhost:8090/ua/logout
spring:
#  profiles: default
  oauth2:
    sso:
      logout-uri: http://localhost:8090/ua/logout
      logout-redirect: true
      loginPath: /login
      home:
        secure: true
#        path: /**/*.html,/**/*.js,/**/*.css,/**/*.jpg,/**/*.png,/**/*.ico
    client:
      accessTokenUri: http://localhost:8090/ua/oauth/token
      userAuthorizationUri: http://localhost:8090/ua/oauth/authorize
      clientId: sensefy
      clientSecret: sensefysecret
#      scope: openid
#      grant-type: authorization_code
#      clientAuthenticationScheme: form
#      pre-established-redirect-uri: http://localhost:8080
#      use-current-uri: true
    resource:
      userInfoUri: http://localhost:8090/ua/user
      preferTokenInfo: false
#spring:
#  oauth2:
#    sso:
#      home:
#        secure: false
#        path: /,/**/*.html,/**/*.js,/**/*.css
#      loginPath: /
#    client:
#     # accessTokenUri: https://accounts.google.com/o/oauth2/token
#      userAuthorizationUri: https://app.box.com/api/oauth2/authorize
#      clientId: xlso76nzc4epij698icjddyxgn7lsiuq
#      clientSecret: tuLJLkDGSqAzSmfHaw46il3xE4cKRmU0
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: http://localhost:8090/ua/user
#      preferTokenInfo: false      
      
      
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    
    
    
